import random

list_11 = [
    random.randrange(
        1,
        10,
    )
    for i in range(10)
]
print("You have 5 chances to guess a number that has been generated by the computer")
count = 0
while True:
    number = int(input("Enter a number: "))
    if number in list_11:
        print("Found")
        break
    else:
        print("Not found")
        if count > 5:
            print("You have no more chances, Your score is 0%")
            break
        count += 1

print(
    f"The list contained: {list_11} and you found one of the numbers in {count} attempts. Your score is {(5-count)/5 * 100}%"
)
